### ISSUE TITLE
feature requests: add close tab without unpining it

### ISSUE THREAD

**Issue by Younex-hq** [JLBlk/Zen-Themes#1]
please add an option to **close** a pinned tab **without unpinning it** from the pinned section

**Comment by JLBlk** [comment]
Hi, unfortunately i cant add this due to the limitations of CSS. You can however use a firefox extension like UnloadTabs ( https://addons.mozilla.org/de/firefox/addon/unload-tabs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search ) to unload/close pinned tabs without unpinning them.
