### ISSUE TITLE
[Feature Request] An option to lock the URL of each pinned tab.

### ISSUE THREAD

**Issue by Bammcool2011** [JLBlk/Zen-Themes#16]
Hello, I would like to suggest adding a feature to lock the URL for **SuperPins**. For example, if I pin a tab (e.g. google.com) and then search for something, whenever the URL changes, when I reopen ZEN and go to the pinned tab, it will still navigate to the original URL that I pinned.

Thank you :D

**Comment by JLBlk** [comment]
Hey, I really like the idea, however I'm afraid that isn't really possible at the moment due to the limitations of CSS. I however heard mauro (the dev behind zen) think about implementing a Zen Plugins function in the future similar to the Theme/Mod store, but with the power of Javascript, which might be able to turn your idea into reality.
Thank you for the suggestion though :D
