### ISSUE TITLE
[Bug] SuperGradient Theme Blocks Left-Click Interactions on Non-UI Elements

### ISSUE THREAD

**Issue by SmallPpBigWorld** [JLBlk/Zen-Themes#19]
**Affected Theme**
- Name: SuperGradient
- Version: v1.1.0

**Affected Theme Settings**
- No specific theme settings were modified; the issue persists with default settings.

**Zen Version**: 1.0.1-a5 (64-bit)

**System OS**: Windows 11

**Describe the bug**  
When the *SuperGradient* theme is installed and enabled, left-clicking on anything other than browser UI elements results in no interaction or response from the page. Essentially, the theme prevents user actions on non-UI elements, rendering them unclickable.

**To Reproduce**
1. Install the *SuperGradient* theme.
2. Enable the theme.
3. Attempt to left-click on any page element (e.g., buttons, links) outside of the browser's native UI (address bar, bookmarks, etc.).
4. Observe that the left-click does not register.

**Expected behavior**  
Left-clicking on interactive elements within a webpage (buttons, links, etc.) should trigger the expected interaction or action. The theme should not block or interfere with regular page functionality.

**Screenshots/Videos**  
[Attach any screenshots or screen recordings that illustrate the issue, if available.]

**Additional context**  
This issue seems to be limited to non-browser UI elements, as UI elements like the address bar and bookmarks still respond correctly to left-clicks. No other themes or extensions were enabled during testing, ensuring that the issue is isolated to *SuperGradient*. It is unclear whether specific theme settings could be responsible, but this behavior persists after a fresh install of both the theme and browser.

**Comment by JLBlk** [comment]
Hmm, weird. Have you tested it by creating a new test profile, only installing SuperGradient and seeing if the issue persists? (Although if you even freshly installed the browser the issue is even more weird)
I tried to reproduce it, but i wasn't able to :(  
Do you know your way around the mods folders in zen a bit? Maybe try copying the code of this repo (which has some small changes, that aren't in zen yet) into the theme file. I can also send a quick tutorial if you want
