### ISSUE TITLE
[Superpins] Light theme has too dark boxes?

### ISSUE THREAD

**Issue by Donnnno** [JLBlk/Zen-Themes#2]
Hey!
Loving the Superpins you've made for Zen. One thing is kinda buggin me tho, and that's the light theme color:

![image](https://github.com/user-attachments/assets/0686bb60-db20-42f4-a67f-2c676ddf2481)

The boxes are too present in my opinion. 

What's your opinion? :)

**Comment by JLBlk** [comment]
Hey, thanks for the kind words. Regarding the colors, i completely forgot about light theme when developing the theme and only tested it on dark theme. I've already changed this (since someone else also mentioned this) along with some other things, however the update (pull request) is still waiting for approval by the dev. Here's the pull request if you wanna see what i changed: https://github.com/zen-browser/theme-store/pull/226 
Keep in mind that it could take some time before the pr gets approved because only the dev (mauro) can do it and he's quite busy with the browser, but as soon as it gets approved you'll only need to check for updates in the theme store settings page and everything should work

**Comment by Donnnno** [comment]
Ah thanks, didn't know you already fixed it! Great work :)

**Comment by JLBlk** [comment]
Hey, the update/pr has been merged, the boxes should now be darker in light theme along with some other stuff!
