### ISSUE TITLE
 [Feature Request] Keep the same pages pins 

### ISSUE THREAD

**Issue by NoozPrime** [JLBlk/Zen-Themes#23]
i would like to be able to always keep the original page that i pin so when i use the pins no matter what the page is gonna be the same so exemple i put https://www.youtube.com/ and i  go on a video i don't want the video to be the pin i want the original https://www.youtube.com/

**Comment by JLBlk** [comment]
Hey, unfortunately this is not possible with only css due to its limitation. There's still hope though, it seems that someone created a pull request to integrate this functionality in the browser itself ( https://github.com/zen-browser/desktop/pull/1848 ) We can only hope that this gets merged or implemented in a similar way
