### ISSUE TITLE
[Feature Request] Page action-buttons slide in when cursor is on top

### ISSUE THREAD

**Issue by Bout2GitIt** [JLBlk/Zen-Themes#25]
**The related Mod/Theme:** Super URL Bar

**Your Enhancement Suggestion/Feature Request**:

One of my fav CSS tweaks from Firefox lets the page action-buttons slide in when I need them, and keeps them hidden otherwise. Feels like it could be a great addition to Super URL Bar. I borrowed it from here: https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/page_action_buttons_on_hover.css 

The CSS code is here:

` 
#page-action-buttons{ padding-inline-start: 8px }

	.urlbar-page-action{
	  margin-inline-end: calc(-16px - 2 * var(--urlbar-icon-padding) );
	  opacity: 0;
	  transition: margin-inline-end 100ms linear, opacity 200ms linear;
	}

	#page-action-buttons:hover > .urlbar-page-action,
	.urlbar-page-action[open],
	.urlbar-page-action[open] ~ .urlbar-page-action{
	  opacity: 1;
	  margin-inline-end: 0px !important;
	} 

`

**Comment by JLBlk** [comment]
Great Idea! Would you say it's better if the buttons appear if you hover over them or over the whole url bar?

**Comment by Bout2GitIt** [comment]
I've been using it on Firefox where it just reveals if you hover over the
buttons. It's great!

I don't know how it will affect the centered URL text, though.

**Comment by JLBlk** [comment]
So, i implemented it now but after hovering over the whole url bar, i would have liked it to be only when hovering over the like buttons area, but due to some buttons there not being siblings in the code that didn't work, and hovering over the single button felt a bit weird, since they are pretty small and you'd have to find them first. 
Maybe i'll change it in the future but now that seemed best imo.
The option to show them on hover will be available as soon as the pull request above gets merged :)
Thanks a lot for the suggestion!

**Comment by Bout2GitIt** [comment]
Thank YOU!
--
Sent in motion.
