### ISSUE TITLE
[Bug] [Super URL Bar] URL text shifts when hidden icons added / removed

### ISSUE THREAD

**Issue by sjclayton** [JLBlk/Zen-Themes#29]
**Affected Theme**
 - Super Url Bar
 - Version 1.3.0

**Affected Theme Settings**
- Center URL text / Hiding right icons

**Zen Version**: 1.0.1-a.7
**System OS**: Linux

**Describe the bug**

If you have the URL text centered and enable hiding of icons on the right side, as you are navigating sites and those hidden icons are being added and removed when the functions enabled / changed in the background (ie. Zoom, Picture-in-Picture, etc), the URL text noticeably shifts back and forth left to right.

**To Reproduce**

Enable centering URL text and then hide icons on the right side. Observe URL text shifting back and forth when icons are added or removed while they are hidden.

**Expected behavior**

URL text does not move when icons are added / removed when hidden.

**Comment by JLBlk** [comment]
Yes. first of all this also happens when not hiding the icons, but i understand the issue. The problem is that i have only 2 options (that i know of) to hide these icons. One way is by removing them completely from the browser, so that they basically don't exist and the other way is by simply making them invisible. The difference is that when just making them invisible, if you only hide the reading mode icon. there would simply be a blank spot with empty space between the star and shield icon. 
Removing the icon completely would fix that, but in turn create the shifting when the buttons appear.
I came to the conclusion to use the 1. option (removing competely) for hiding buttons without hover, while using the 2.option (making invisible) for hiding with hover.
I hope you understand my struggle with both of these options. I don't think there is a better way to do it right now, but i'm no expert, maybe i'll find a better way in the future, sry
