### ISSUE TITLE
[Feature Request] [SuperGradient] - bookmarks area

### ISSUE THREAD

**Issue by Johnjx** [JLBlk/Zen-Themes#35]
**The related Mod/Theme:**

SuperGradient

**Your Enhancement Suggestion/Feature Request**

Want gradient to extend to the bookmarks bar.
I use & reveal the bookmarks when needed, but that area is black. 👍

![Screenshot 2024-10-15 155418](https://github.com/user-attachments/assets/bb239637-1397-45a5-945d-c27ce20cfda3)

**Comment by JLBlk** [comment]
The gradient should extend to the bookmarks bar normally 

![image](https://github.com/user-attachments/assets/aa0937f5-1c7d-4d3c-a0a4-af0af69f9b7b)

Here it works for me.
It could in your case be conflicting with another mod like bookmark toolbar tweaks. There is a workaround for that though. Enable the setting "Make the bookmarks toolbar transparent (only works with expand features)" at the bottom of the mod settings of "bookmark toolbar tweaks". This makes the gradient work on the bookmarks toolbar again.
I hope this helped and resolved this issue. If so tell me please, so that i can close the issue

**Comment by Johnjx** [comment]
Yes, fixed!
Thanks.

**Comment by YouCanTouCan** [comment]
Just to add to this:

The workaround describes does work, but sadly the conflict appears again if you select either of the "Expand" options in the settings of Bookmark Toolbar Tweaks. The first image shows it working without the Expand options selected, the second with both Expand options enabled, and the bar expanded. You can see the "Import Bookmarks" on the far left awkwardly hovering over the edge. It appears that with the Expand options enabled, the expanded bookmarks toolbar becomes transparent instead of having the gradient theming. No idea if this is something fixable within this mod or if it would need to be fixed in the Bookmark Toolbar Tweaks mod instead, just thought that I would mention it.

![image](https://github.com/user-attachments/assets/41c47214-812a-464f-8b29-7d1ad07f6a2c)
![image](https://github.com/user-attachments/assets/4874ea8e-5ae0-40f0-86b9-1ada3acf1e76)

**Comment by JLBlk** [comment]
Yeah, it's pretty hard to add compatibility with other mods. In this case the "bookmark toolbar tweaks" mod is using the "zen.colors.tertiary" variable. But since some zen updates ago, it's not possible to assign a different value to the "zen.colors.tertiary" variable anymore, so i had to apply the gradient to all the individual elements instead of the "zen.colors.tertiary" variable. But any mod that needs change the colors in any way is understandably using the "zen.colors.tertiary" variable, which breaks the gradient.
It's rather unlikely that this conflict between SuperGradient and Bookmark Toolbar Tweaks can be resolved, maybe i'll find a way in the future, but i'll close this issue for now, sry
