### ISSUE TITLE
[Feature Request] [SuperGradient] Color picker for simplified gradient creation

### ISSUE THREAD

**Issue by Hikiru** [JLBlk/Zen-Themes#37]
**The related Mod/Theme:** 
SuperGradient

**Your Enhancement Suggestion/Feature Request**
Add a color picker to more easily adjust gradients, if even possible. Additionally, you could have a "simple" color picker option where you choose one base color and the extension automatically makes the gradient, similar to arc.

**Comment by JLBlk** [comment]
Hey, sry for the late answer first of all,
unfortunately it's not possible for me to include a color picker due to the limits of Mods, that would have to be implemented in Zen itself. However Zen is getting native support for gradients with a color picker like interface as you can see here: https://www.reddit.com/r/zen_browser/comments/1gc33hc/make_it_spin_early_but_working_prototype_please/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
