### ISSUE TITLE
[Bug] Super URL Bar theme makes the new Glance feature unusable

### ISSUE THREAD

**Issue by jarz76** [JLBlk/Zen-Themes#43]
**Affected Theme**
 - Name: Super Url Bar
 - Version 1.4.1

**Affected Theme Settings**
- x

**Zen Version**: 1.0.1-a.17 

**System OS**:  Windows 11

**Describe the bug**
The Super URL Bar theme makes the new Glance feature in Zen Browser unusable.

**To Reproduce**
1. Alt + Left Click Mouse the URL
2. The glance features partially works, it shows the preview window, but the Close and Expand buttons are unclickable.

**Expected behavior**
The buttons should be clickable. Clicking the Expand button should open the preview in a new tab, and clicking the Close button should close the preview window.

**Screenshots/Videos**

https://github.com/user-attachments/assets/819635b3-bfce-4035-815a-10b704592d9e

**Comment by JLBlk** [comment]
Thanks a lot for the report! I'll fix it right away.
If anyone's curious, it's because of the clip-path. In the past zen versions, i needed to use clip-path to get the background blur working, but luckily it's not needed anymore, so i can remove it anyway, which will fix this issue.
For now you can just disable background blur, but i'll update it asap
