### ISSUE TITLE
[Feature Request] Add ability to "prefer" zen workspace gradient over super gradient

### ISSUE THREAD

**Issue by plutonium-239** [JLBlk/Zen-Themes#63]
**The related Mod/Theme:**
SuperGradient

**Your Enhancement Suggestion/Feature Request**
This would be a toggle in the options: **Prefer workspace gradient over SuperGradient**

Essentially, SuperGradient only shows when a workspace does not have a defined (zen) gradient. When it does, give preference to the user defined zen gradient.

Also, it doesn't show up in the sidebar when expand on hover is enabled.

**Comment by JLBlk** [comment]
Sry for the late answer but SuperGradient is no longer on the mods store

**Comment by plutonium-239** [comment]
What?

**Comment by JLBlk** [comment]
Yeah, but Zen's native gradients are good enough, you're probably right regarding the presets, but overall having  a mod that's too similar to the native implementation, just less intuitive wouldn't make much sense. When creating the mod I hoped that gradients would get a native implementation some day which they did, which is why it's of the store. Sry

**Comment by plutonium-239** [comment]
Well, no need for a sorry. Thank you for making this in the first place!
