### ISSUE TITLE
Super Url Bar isnt working at all.....

### ISSUE THREAD

**Issue by Ibrahim-Faisal15** [JLBlk/Zen-Themes#8]
I tried reinstalling it multiple times but still.

**Comment by JLBlk** [comment]
Did you enable the corresponding settings in Zens Theme settings?

**Comment by keiothic** [comment]
![image](https://github.com/user-attachments/assets/b778bb4e-4c88-43a6-9a8b-6fcfc18c83ec)
Just in case it wasn't clear for people who came from vanilla Firefox

**Comment by ivanstrassberg** [comment]
background blur does not work for me...

**Comment by JLBlk** [comment]
Hmm, weird. Have you checked if any other themes or extensions may be conflicting. Does anyone else have this problem (with background blur not working)?

**Comment by ivanstrassberg** [comment]
yeah, something definitely was conflicting. I removed all i had, now it works as intended. I'll reinstall everything back and let you know which theme caused the issue.

**Comment by ivanstrassberg** [comment]
https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6
appears to be the cause
i also tested it with the floating urlbar, and it also breaks the blur there

**Comment by JLBlk** [comment]
hmm, you're right, the disabled rounded corners breaks the blur (it still makes the bg a tiny bit darker but blur is gone). I looked into its source code a bit and when removing the clip path attribute from it's theme (which is the most essential part of the theme lol) the blur works again, so that seems to be the problem. However i don't know a way to fix it right now since my knowledge with that isn't that advanced, maybe i'll find a fix later but i dont know yet. 
Regarding floating urlbar, on my end the blur works without problems there
